spring:
  application:
    name: pteam

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        use_sql_comments: true

  flyway:
    enabled: true
    baseline-version: 0
    baseline-on-migrate: true
    out-of-order: true
    locations: classpath:db/migration, classpath:db/data

logging.level.org:
  springframework: info
  hibernate:
    SQL: debug
    orm.jdbc.bind: trace

jwt:
  secret: ${JWT_SECRET}
  access-token-ttl: 3600000    # 1시간(60 * 60 * 1000)
  refresh-token-ttl: 604800000   # 7일(7 * 24 * 60 * 60 * 1000)